cod_behavior:
  ros__parameters:
    cod_bt_path:
      "COD_Behavior/cod_bt/tactical_front_tree.xml"
    enable_groot2: true
    groot2_port: 5555
    zone_mode_topic: "/sentry_mode_cmd"
    front_patrol_csv: "/home/nucshao/Climber_slam_2026_NAV/src/rm_bringup/wps/test.csv"
    fortress_route_csv: "/home/nucshao/Climber_slam_2026_NAV/src/rm_bringup/wps/back.csv"
    nav_pose:
      home:
        frame_id: "map"
        position:
          x: -0.396
          y: -2.48
          z: 0.0
        orientation:
          w: 1.0

      fortress:
        frame_id: "map"
        position:
          x: 4.81
          y: 1.4
          z: 0.0
        orientation:
          w: 1.0

      main:
        frame_id: "map"
        position:
          x: 4.59319
          y: -3.16278
          z: 0.0
        orientation:
          w: 1.0

      main1:
        frame_id: "map"
        position:
          x: 5.05161
          y: 0.5
          z: 0.0
        orientation:
          w: 1.0

    D_patrol_pose:
      first:
        frame_id: "map"
        position:
          x: 2.0
          y: -1.0
          z: 0.0
        orientation:
          w: 1.0

      second:
        frame_id: "map"
        position:
          x: -2.0
          y: -1.0
          z: 0.0
        orientation:
          w: 1.0

    A_patrol_pose:
      first:
        frame_id: "map"
        position:
          x: 3.05161
          y: -4.0
          z: 0.0
        orientation:
          w: 1.0

      second:
        frame_id: "map"
        position:
          x: 1.05161
          y: -4.0
          z: 0.0
        orientation:
          w: 1.0
